"use client";

import "../styles/globals.css"; // Tailwind CSS 적용
import type { AppProps } from "next/app";
import Head from "next/head";
import Header from "@/components/Layout/Header";
import { usePathname } from "next/navigation";
import styled from "styled-components";

const RightLayout = styled.div`
  max-width: 414px;
  height: 736px;
  border: 1px solid red;
`;

export default function App({ Component, pageProps }: AppProps) {
  const path = usePathname();
  return (
    <RightLayout>
      <Head>
        <title>kiloflow</title>
        <meta name="description" content="Generated by Next.js" />
        {/* Other meta tags */}
      </Head>
      <div>
        {path === "/auth/join" || path === "/auth/login" ? (
          <Component {...pageProps} />
        ) : (
          <>
            <Header />
            <Component {...pageProps} />
            {/* <Footer /> */}
          </>
        )}
      </div>
    </RightLayout>
  );
}
