import "../styles/globals.css"; // Tailwind CSS 적용
import type { AppProps } from "next/app";
import styles from "../styles/components.module.css";
import Head from "next/head";
import Header from "@/components/Layout/Header";

export const metadata = {
  title: "kiloflow",
  description: "Generated by Next.js",
};

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <div>
        <header>
          <Header />
        </header>
        <main>
          <Component {...pageProps} />
        </main>
        {/* <footer>
          <Footer />
        </footer> */}
      </div>
    </>
  );
}
